### PR TITLE
Added getnoisekey - function to generate noiskey based on a password

### PR DESCRIPTION
**Pull request by pdogg**
generate a "noisekey" based on the password... allows for a more "random" stego situation

I don't know the cryptographic implications of this change. Looking for evaluations and thoughts

### CODE REVIEW

**Comment by pdogg** [comment]
Not merging this... I'll use a key derivation algorithm instead...

**Comment by TheDukeZip** [comment]
I like the idea behind this so the locations of the steg data is not always the same. If we need to do something with a salt then that is an additional piece of information that needs to be shared between the parties

**Comment by pdogg** [comment]
I think it can be done with just the password and the legit message :) I'll
use the legit message as a salt and the password as the password in
somethink like PKCS#5

**Comment by TheDukeZip** [comment]
good idea

**Comment by pdogg** [comment]
I dunno.. the more I think about this the more I want to pull it in now. I agonized over this on the way home. There may be a "better solution" down the road. My reasons:
1. The whole password hash would never leak. I was wrong above. We don't change the part of the key used here.
2. We are leaking 72 bits of the hash of the password. These 72 bits are out of order.
3. Having the placements of the stego symbols dependent on the password is helpful otherwise you do need to exchange two secrets (password and placement). Doing something like this makes it only dependent on password.

I may change my vote to pull this in and go for the transition to an stronger key derivation algorithm as an optional. This is compromise but so is everything else...

**Pull request merged**
